In [ ]:
#Arrays: 1D,2D,3D,4D
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a)), print(a.ndim)
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
print(type(a1)),print(a1.ndim)
a2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a2)
print(type(a2)),print(a2.ndim)
a3=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(a3)
print(type(a3)),print(a3.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
<class 'numpy.ndarray'>
4


(None, None)

In [ ]:
x = np.array([[1,23,3],[3,4,5],[4,5,6]])
print(x), 
print(x.ndim)

x1=np.array([[[1,2,3]]])
print(x1)
print(x1.ndim)

x2=np.array([[[[1,2,3],[4,5,6]]]])
print(x2)
print(x2.ndim)

x3=np.array([1,2,3])
print(x3)
print(x3.ndim)

[[ 1 23  3]
 [ 3  4  5]
 [ 4  5  6]]
2
[[[1 2 3]]]
3
[[[[1 2 3]
   [4 5 6]]]]
4
[1 2 3]
1


In [ ]:
# ###Zeros
# np.zeros(5)
# np.zeros(100)
# np.zeros((2,4))
# np.zeros((4,2))
z=np.zeros(((2,4,2)))
print(z)
z.ndim

z1=np.zeros((2,4,2))
print(z1)
z1.ndim


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


3

In [ ]:
# ###ones
# np.ones(2)
# o=np.ones((2,2))
# print(o)
# o.ndim

# o1=np.ones((2,2,2))
# print(o1)
# o1.ndim

np.ones((3,1,50))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]]])

In [ ]:
###Identity
np.identity(3)
np.identity(1)
np.identity(5)
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
###Arange
s=np.arange(4)
s1=np.arange(1,10)
s2=np.arange(1,10,2)
s3=np.arange(10,1,-1)
print(s,s1,s2,s3)


[0 1 2 3] [1 2 3 4 5 6 7 8 9] [1 3 5 7 9] [10  9  8  7  6  5  4  3  2]


In [ ]:
###Empty : some random elements in array of given range.
np.empty(5)          # 5 random elements
np.empty((5,2))      # a matrices of 5*2, i.e 5 rows and 2 columns
np.empty((2,5,2))    # first 2 is showing number of matrices, (5,2) is showing 5*2 matrix with 5 rows and 2 colums


array([[[4.66568854e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
###linspace
np.linspace(2,5)      # random elements  b/w 2 to 5 but at equal interval
np.linspace(2,5,10)   #start point =2, end point=5, total elements = 10 at equal interval b/w 2 to 5

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [ ]:
###sum
arr= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0)) 
print("sum of arr(axis = 0 : ", arr.sum(axis=0))
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 15 18]]
Sum of arr(axis = 0) :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of arr(axis = 0 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of arr(axis = 1) :  [[12 15 18]]


In [6]:
### Transpose, shape, length
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.T)
print(a.shape)
print(a.dtype)
print(len(a))
a.ndim



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)
int64
3


2

In [15]:
myarr=np.array(1)
print(myarr)
print(myarr.ndim)
# print(len(myarr))

### elemnts specification
myarr = np.array([2,3,6,7])
print(myarr)
myarr[2]=200
print(myarr)





[2 3 6 7]
[  2   3 200   7]
